### ISSUE TITLE
menoh_model_data_add_attribute_[int|ints]_to_current_node value type mismatch

### ISSUE THREAD

**Issue by msakai** [pfnet-research/menoh#117]
`menoh_model_data_add_attribute_int_to_current_node` takes `int32_t` as integer value while `menoh_model_data_add_attribute_ints_to_current_node` takes `int`s values.

https://github.com/pfnet-research/menoh/blob/cfb243b26b1fbd8d16f7f1daadbc66564cab46f9/include/menoh/menoh.h#L143-L149
https://github.com/pfnet-research/menoh/blob/cfb243b26b1fbd8d16f7f1daadbc66564cab46f9/include/menoh/menoh.h#L156-L162

This looks inconsistent.
Is this intended definition?

**Comment by okdshin** [comment]
No. It is a failure. I'll fix it. Thanks pointing out.

**Comment by okdshin** [comment]
I fixed.
