### ISSUE TITLE
mingw packages for mkl-dnn and menoh

### ISSUE THREAD

**Issue by msakai** [pfnet-research/menoh#19]
I made mingw packages for mkl-dnn and menoh.

mkl-dnn
https://github.com/msakai/MINGW-packages/tree/mkl-dnn-0.14/mingw-w64-mkl-dnn

menoh
https://github.com/msakai/MINGW-packages/tree/menoh-1.0.1/mingw-w64-menoh

Binary packages:
https://www.dropbox.com/sh/vkomvo22fsy25h5/AAAOycfx-DP0EFLPiueMxDJIa?dl=0

**Comment by msakai** [comment]
@okdshin Could you take a look at it?
If it seems OK, I'd like to make pull requests to upstream repository.

**Comment by okdshin** [comment]
Oh nice! I checked and it seems no problem. Please PR.

**Comment by msakai** [comment]
Thanks!  I just made PRs.
https://github.com/Alexpux/MINGW-packages/pull/4002
https://github.com/Alexpux/MINGW-packages/pull/4003

**Comment by msakai** [comment]
I withdrawn these pull request because the repository is not accepting packages that builds only for one arch. Maybe we need to consider distributing our packages in different ways ...

BTW:
I noticed that the above MKL-DNN binary package did not work on AppVeyor environment. `Menoh` can be compiled/linked with it, but `menoh_test` failed with `STATUS_DLL_NOT_FOUND`. I tried to debug the problem using `objdump -p`, `ldd` and [dependencywalker](http://www.dependencywalker.com/), but I couldn't figured out the cause.
Therefore, in PR #25, I chose to build MKL-DNN on AppVeyor instead of using the above precompiled MKL-DNN binary package.

**Comment by msakai** [comment]
It seems the problem of my MKL-DNN binary package on `AppVeyor` is caused by `strip`ing `mklml.dll` and `libiomp5md.dll`. 
I uploaded fixed version `mingw-w64-x86_64-mkl-dnn-0.14-3-x86_64.pkg.tar.xz` to the same folder.

**Comment by msakai** [comment]
I succeeded to build MINGW packages of MKL-DNN and Menoh on AppVeyor.

Scripts:
https://github.com/msakai/mkl-dnn/tree/MINGW-package
https://github.com/msakai/menoh/tree/MINGW-package

Example of resulting files:
https://ci.appveyor.com/project/msakai/mkl-dnn/build/1.0.12/artifacts
https://ci.appveyor.com/project/msakai/menoh/build/1.0.109/artifacts

**Comment by msakai** [comment]
Remaining problem was the way of distribution, but I decided to attach those MINGW packages to GitHub release.
