### ISSUE TITLE
add mkdir to retrieve_data.py, and update README.md

### ISSUE THREAD

**Issue by misogil0116** [pfnet-research/menoh#2]
This library is very interesting!
I want to use this library, but an error occurred.
Can I send you a easy pull requests to fix this bug?
I will add mkdir method to retrieve_data.py

I read how to build this library at README.md.
I wonder if it is not `sh retrieve_data.py` but `python retrieve_data.py`.
Thanks.

```
wget https://www.dropbox.com/s/bjfn9kehukpbmcm/VGG16.onnx?dl=1 -O ./data/VGG16.onnx
Traceback (most recent call last):
  File "retrieve_data.py", line 13, in <module>
    wget('https://www.dropbox.com/s/bjfn9kehukpbmcm/VGG16.onnx?dl=1', './data/VGG16.onnx')
  File "retrieve_data.py", line 11, in wget
    urllib.request.urlretrieve(address,  target)
  File "/Users/nishimurataichi/.pyenv/versions/anaconda3-4.1.0/lib/python3.5/urllib/request.py", line 197, in urlretrieve
    tfp = open(filename, 'wb')
FileNotFoundError: [Errno 2] No such file or directory: './data/VGG16.onnx'
```

**Comment by okdshin** [comment]
Thank you!! Although we have not made contribution guide yet, we would like to take your PR.

**Comment by okdshin** [comment]
I merged your PR. Thank you for your interest and contribution!
