### ISSUE TITLE
cmake script does nt check gcc version

### ISSUE THREAD

**Issue by WilliamTambellini** [pfnet-research/menoh#204]
I know the doc/md file correctly requires gcc 4.9 but in case someone tries to use an older gcc then cmake continues and then some (hard to understand for newcomers) compilation errors happen at make/compilation time. 

Should nt the main cmake script check gcc verison ? 

example:

if (CMAKE_COMPILER_IS_GNUCC)
 if (CMAKE_CXX_COMPILER_VERSION VERSION_LESS 4.9)
    message(FATAL_ERROR "blablabla")
 endif()
endif()

**Comment by okdshin** [comment]
Thank you for your report. We will fix `CMakeLists.txt` as you mentioned.
Requirements shoud be checked at cmake time.

**Comment by okdshin** [comment]
This is fixed. Thank you report!
