### ISSUE TITLE
Coverity Scan

### ISSUE THREAD

**Issue by msakai** [pfnet-research/menoh#34]
How about setting up Coverity Scan?
https://scan.coverity.com/

Coverity Scan is famous static analysis tool for C/C++ and several other languages.
It can be used for open source project for free.

**Comment by okdshin** [comment]
It sounds nice. I'll try.

**Comment by msakai** [comment]
Maybe we can avoid the problem by runnning `cov-build` on Travis-CI.
https://scan.coverity.com/travis_ci

Is it possible to invite me to the Coverity Scan dashboard?

**Comment by okdshin** [comment]
OK. I'll invite.

**Comment by okdshin** [comment]
@msakai configured coverity scan with travis ci. Thank you!
