### ISSUE TITLE
menoh_model_get_variable_dims()

### ISSUE THREAD

**Issue by enobufs** [pfnet-research/menoh#48]
In node-menoh, I wrote [this helper function](https://github.com/pfnet-research/node-menoh/blob/v1.1.0/src/model.cpp#L427-L454).  It would be nice if there's a C-API function in menoh something similar (if possible) to the following:
```c
int32_t size;
const int32_t *dims;
ec = menoh_model_get_variable_dims(model_handle, var_name, &size, &dims);
```
Where;
```c
menoh_error_code  menoh_model_get_variable_dims(
    const menoh_model_handle model,
    const char* variable_name, 
    int32_t *size,
    const int32_t **dims);
```

It is sort of combining `_get_variable_dims_size` and `_get_variable_dims_at` all together without having to iterate over `_dims_at` function with its size...
> Assumption: the dims values won't change unless the profile was altered by the app.

**Comment by msakai** [comment]
It's nice for efficiency to avoid repeated lookup with `variable_name` across multiple invocation of `menoh_model_get_variable_dims_at` (at least mentally).

**Comment by okdshin** [comment]
I wonder how to manage the memory pointed by `dims`.

**Comment by msakai** [comment]
I assumed the memory is owned by the model.

**Comment by okdshin** [comment]
I see. I'll modify as that.

**Comment by msakai** [comment]
PR #41 is related as this PR change the type of `dims`.

**Comment by okdshin** [comment]
I've done.
