### ISSUE TITLE
Different pre-processing of VGG16 example

### ISSUE THREAD

**Issue by Hakuyume** [pfnet-research/menoh#53]
Menoh's VGG16 example applies center crop to images and does not subtract mean, where that of Chainer substract mean and does not crop. If this difference is not essential, it is better to follow Chainer's style.

**Comment by okdshin** [comment]
I fixed it. Thank you!

**Comment by okdshin** [comment]
Resize is different. Chainer's one does not crop.

**Comment by okdshin** [comment]
PR to fix it is merged.
