### ISSUE TITLE
Failed to generate onnx.pb.h when LINK_STATIC_LIBPROTOBUF is enabled

### ISSUE THREAD

**Issue by msakai** [pfnet-research/menoh#79]
`external/onnx/onnx/onnx.pb.h` is generated here in `CMakeLists.txt`:
https://github.com/pfnet-research/menoh/blob/a14ba333a0a7556d2f78b49a9cf102eacb7a18e0/CMakeLists.txt#L61

But if `LINK_STATIC_LIBPROTOBUF` is enabled, `protoc` has not been built yet.

It seems that we need to run the command during `make` instead of during `cmake`.

**Comment by Hakuyume** [comment]
I think `protoc` should be invoked in `make` but its existence should be checked in `cmake`. Only if static link is enabled, this check can be skipped.
